### PR TITLE
Add environments config for testing current version of py/django.

### PR DESCRIPTION
**Pull request by willywongi**
This adds tests for the current supported version of Python and Django, while removing old, unsupported version (Django < 3.2, python < 3.8).
I used this tables to infer what versions are supported: [Python](https://devguide.python.org/versions/) and [Django](https://www.djangoproject.com/download/#supported-versions).

Because of removing support for older py/django, I bumped the version number to 0.15.

### CODE REVIEW

**Comment by spookylukey** [comment]
Thanks for the PR!

My normal policy is to drop support only when I've got a reason to do so, because this often gives more flexibility to people when upgrading, or when considering a move to start using the library.  So I tend to keep the old versions until they start causing significant problems.

The other changes all look good. Could you change this PR so it doesn't drop support for any versions? There is also no need for a new release because it doesn't change any code, and you can install on more recent versions of Python/Django without any problem as far as I'm aware, so the history will need fixing as I won't be doing a release immediately.

Thanks!

**Comment by willywongi** [comment]
> My normal policy is to drop support only when I've got a reason to do so
That's so very reasonable :) I'm bringing back test environments as they were, and adding py311, py312 on Django LTS and current versions (3.2, 4.2, 5).

**Comment by spookylukey** [comment]
In the diff in setup.cfg, it is still showing unwanted changes, including `install_requires =  Django>=3.2` which will block installation for people on older Django, could you have a look? Thanks!

**Comment by spookylukey** [comment]
This got a bit messy, so I squashed/rebased your commits in #10 . Thanks!

**Comment by willywongi** [comment]
I'm sorry I wanted to help but in the end I had you do *more* work instead. So let me say thank you: I learned something along the way. Thank you!

**Comment by spookylukey** [comment]
> I'm sorry I wanted to help but in the end I had you do _more_ work instead. So let me say thank you: I learned something along the way. Thank you!

No worries, that's what it's all about, thanks for persevering when I asked for changes!

**Comment by spookylukey** [comment]
In terms of making less work for yourself (or other people) in the future, here are my tips:

- make commits into the smallest possible logical changes e.g. one commit for adding new versions, a separate commit for dropping versions
- this means that if you later realise you want to remove some changes, you can use git interactive rebase to remove them individually just by dropping the commits, rather than attempting a revert. (This sometimes still involves a bit of merging and conflicts, but sometimes you get lucky and its really easy).

  Rebasing like this will require a "force push" to the branch, but that's usually fine if no-one else is working on it.

- You can also use "fixup" commits in git to change an earlier commit, but it's a bit advanced. (I'm using [magit](https://magit.vc/) which makes it easy, otherwise I haven't bothered).

Obviously some of these things are easier with hindsight!

**Pull request closed without merging**
